### ISSUE TITLE
Bad SQL queries when requesting employees

### ISSUE THREAD

**Issue by aceade** [aceade/corpolc-inventory#17]
**OLD - ignore these**
Trying to run the JAR file after building results in the following error:

> Exception  in thread "main" java.lang.NoClassDefFoundError: org/springframework/boot/SpringApplication
	at com.aceade.corpolc.inventory.config.Application.main(Application.java:21)
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.SpringApplication
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more

Since I can't run this, I can't test that it works!

**Comment by aceade** [comment]
**OLD - IGNORE**
Trying to import dependency management from spring-boot 2.0.5.RELEASE now results in compilation failures because "package org.apache.log4j does not exist".

**Comment by aceade** [comment]
Turns out I was running the wrong command! `mvn spring-boot:run` instead of running the JAR file works. However, there are issues with the SQL queries - I'll convert this to update them.

**Comment by aceade** [comment]
Seems to be working now.
